name: Deploy hosting firebase

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        args: deploy --only hosting
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: mylove181099
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}